### ISSUE TITLE
Robit: Review & Type Hinting (1.0hr)

### ISSUE THREAD

**Issue by wesleyhstratusadv** [stratusadv/robit#14]
- [x] Review project structure and note changes.
- [x] Add type hinting.

**Comment by nathanjstratusadv** [comment]
Did a full refactor with type hinting (there was an outstanding circular import in the chronological module that I could not type hint at the moment.

Questions

- Second Operation for Chron ?
- API ?
- Webhook ?
- Shared memory Object instead of Socket ?
- Some type of thread controller that can watch it self and restart if required ?
- How our exceptions caught in threads (do they leak out or except into the main thread) ?

**Comment by nathanjstratusadv** [comment]
Finished and moved everything in notes into new issues.
